pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', 
                credentialsId: 'github_access_token',
                url: 'https://github.com/SymulKabir/somachartv-express.js.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building...'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }
        

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }
}
